import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";

export interface Student {
  id: string;
  name: string;
  created_at: string;
  student_code?: string | null;
  student_group?: string | null;
  assigned_teacher?: string | null;
  gender?: string | null;
  status?: string | null;
  // Progress tracking
  last_progress_month?: string | null;
  progress_due_month?: string | null;
  progress_due_since_date?: string | null;
  // Group A
  qaidah_level?: number | null;
  duas_status?: string | null;
  // Group B
  quran_juz?: number | null;
  quran_completed?: boolean | null;
  tajweed_level?: number | null;
  tajweed_completed?: boolean | null;
  // Group C
  hifz_sabak?: number | null;
  hifz_s_para?: number | null;
  hifz_daur?: number | null;
  hifz_graduated?: boolean | null;
}

export const useStudents = (enabled: boolean = true, maktab?: "boys" | "girls", groupCode?: string, groupCodes?: string[]) => {
  const queryClient = useQueryClient();

  const { data: students = [], isLoading } = useQuery({
    queryKey: ["students", maktab, groupCode, groupCodes],
    queryFn: async () => {
      let query = supabase
        .from("students")
        .select("*")
        .neq("status", "left")
        .order("name");
      
      if (maktab) {
        query = query.eq("maktab", maktab);
      }
      
      // Filter by group(s)
      if (groupCodes && groupCodes.length > 0) {
        // Multiple groups selected
        query = query.in("student_group", groupCodes);
      } else if (groupCode) {
        // Single group
        query = query.eq("student_group", groupCode);
      }
      
      const { data, error } = await query;
      
      if (error) throw error;
      return data as Student[];
    },
    enabled,
  });

  const addStudent = useMutation({
    mutationFn: async (name: string) => {
      if (!maktab) {
        throw new Error("Maktab is required to add a student");
      }

      // Insert into database - student_code is auto-generated by DB trigger
      const insertData: {
        name: string;
        gender?: string;
        maktab?: string;
        student_group?: string;
      } = { 
        name,
        gender: maktab,
        maktab: maktab,
      };

      // For boys maktab, assign the group
      if (groupCode && maktab === "boys") {
        insertData.student_group = groupCode;
      }
      
      const { data, error } = await supabase
        .from("students")
        .insert(insertData)
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["students", maktab, groupCode] });
      
      toast({
        title: "Student added",
        description: `${data.student_code} - ${data.name} has been added successfully.`,
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: "Failed to add student. Please try again.",
        variant: "destructive",
      });
      console.error("Error adding student:", error);
    },
  });

  return {
    students,
    isLoading,
    addStudent: addStudent.mutate,
    isAdding: addStudent.isPending,
  };
};
